name: deploy website
on:
  pull_request:
    types:
      - auto_merge_enabled
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.txt"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          vercel-args: '--prod' #Optional